// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (id, user_id)
VALUES (?, ?)
RETURNING id, created_at, user_id
`

type CreateAdminParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin, arg.ID, arg.UserID)
	var i Admin
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UserID)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins
WHERE user_id = ?
`

func (q *Queries) DeleteAdmin(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAdmin, userID)
	return err
}

const isAdmin = `-- name: IsAdmin :one
SELECT user_id FROM admins
WHERE user_id = ?
`

func (q *Queries) IsAdmin(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, isAdmin, userID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
