// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type User struct {
	ID        interface{}
	CreatedAt string
	UpdatedAt string
	Username  string
	Password  string
}
