// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type RefreshToken struct {
	ID        interface{}
	CreatedAt string
	UpdatedAt string
	Token     string
	RevokedAt sql.NullString
	ExpiresAt string
	UserID    interface{}
}

type User struct {
	ID        interface{}
	CreatedAt string
	UpdatedAt string
	Username  string
	Password  string
}
