// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tldrs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTLDR = `-- name: CreateTLDR :one
INSERT INTO tldrs (id, title, content, user_id)
VALUES (?, ?, ?, ?)
RETURNING id, created_at, updated_at, title, content, user_id
`

type CreateTLDRParams struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateTLDR(ctx context.Context, arg CreateTLDRParams) (Tldr, error) {
	row := q.db.QueryRowContext(ctx, createTLDR,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.UserID,
	)
	var i Tldr
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const deleteTLDR = `-- name: DeleteTLDR :exec
DELETE FROM tldrs
WHERE user_id = ?
    AND id = ?
`

type DeleteTLDRParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DeleteTLDR(ctx context.Context, arg DeleteTLDRParams) error {
	_, err := q.db.ExecContext(ctx, deleteTLDR, arg.UserID, arg.ID)
	return err
}

const deleteTLDRById = `-- name: DeleteTLDRById :exec
DELETE FROM tldrs
WHERE id = ?
`

func (q *Queries) DeleteTLDRById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTLDRById, id)
	return err
}

const getAllTLDRs = `-- name: GetAllTLDRs :many
SELECT id, created_at, updated_at, title, content, user_id FROM tldrs
`

func (q *Queries) GetAllTLDRs(ctx context.Context) ([]Tldr, error) {
	rows, err := q.db.QueryContext(ctx, getAllTLDRs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tldr
	for rows.Next() {
		var i Tldr
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTLDRByIDAndUser = `-- name: GetTLDRByIDAndUser :one
SELECT id, created_at, updated_at, title, content, user_id FROM tldrs
WHERE user_id = ?
    AND id = ?
`

type GetTLDRByIDAndUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetTLDRByIDAndUser(ctx context.Context, arg GetTLDRByIDAndUserParams) (Tldr, error) {
	row := q.db.QueryRowContext(ctx, getTLDRByIDAndUser, arg.UserID, arg.ID)
	var i Tldr
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const getTLDRById = `-- name: GetTLDRById :one
SELECT id, created_at, updated_at, title, content, user_id FROM tldrs
WHERE id = ?
`

func (q *Queries) GetTLDRById(ctx context.Context, id uuid.UUID) (Tldr, error) {
	row := q.db.QueryRowContext(ctx, getTLDRById, id)
	var i Tldr
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const getTLDRsByUser = `-- name: GetTLDRsByUser :many
SELECT id, created_at, updated_at, title, content, user_id FROM tldrs
WHERE user_id = ?
`

func (q *Queries) GetTLDRsByUser(ctx context.Context, userID uuid.UUID) ([]Tldr, error) {
	rows, err := q.db.QueryContext(ctx, getTLDRsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tldr
	for rows.Next() {
		var i Tldr
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTLDRTitle = `-- name: UpdateTLDRTitle :one
UPDATE tldrs
SET title = ?
WHERE user_id = ?
    AND id = ?
RETURNING id, created_at, updated_at, title, content, user_id
`

type UpdateTLDRTitleParams struct {
	Title  string    `json:"title"`
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTLDRTitle(ctx context.Context, arg UpdateTLDRTitleParams) (Tldr, error) {
	row := q.db.QueryRowContext(ctx, updateTLDRTitle, arg.Title, arg.UserID, arg.ID)
	var i Tldr
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Content,
		&i.UserID,
	)
	return i, err
}
